esphome:
  name: space-control

esp32:
  board: nodemcu-32s

time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal Strengh"
    update_interval: 60s

switch:
  - platform: template
    name: Light
    id: switch1
    turn_on_action:
      - light.addressable_set:
          id: indicator_lights
          range_from: 2
          range_to: 2
          red: 80%
          green: 0%
          blue: 0%
          white: 0%
    turn_off_action:
      - light.addressable_set:
          id: indicator_lights
          range_from: 2
          range_to: 2
          red: 0%
          green: 0%
          blue: 0%
          white: 1%
  - platform: template
    name: Music
    id: switch2
    turn_on_action:
      - light.addressable_set:
          id: indicator_lights
          range_from: 1
          range_to: 1
          red: 0%
          green: 80%
          blue: 0%
          white: 0%
    turn_off_action:
      - light.addressable_set:
          id: indicator_lights
          range_from: 1
          range_to: 1
          red: 0%
          green: 0%
          blue: 0%
          white: 1%
  - platform: template
    name: Good mood
    id: switch3
    turn_on_action:
      - light.addressable_set:
          id: indicator_lights
          range_from: 0
          range_to: 0
          red: 0%
          green: 0%
          blue: 80%
          white: 0%
    turn_off_action:
      - light.addressable_set:
          id: indicator_lights
          range_from: 0
          range_to: 0
          red: 0%
          green: 0%
          blue: 0%
          white: 1%


binary_sensor:
  - platform: gpio
    id: button_i1
    name: Light ON
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on: 200ms
        - delayed_off: 200ms
    on_press:
        then:
          - switch.turn_on: switch1
  - platform: gpio
    id: button_i2
    name: Music ON
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on: 200ms
        - delayed_off: 200ms
    on_press:
        then:
          - switch.turn_on: switch2
  - platform: gpio
    id: button_i3
    name: Good spirits ON
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on: 200ms
        - delayed_off: 200ms
    on_press:
        then:
          - switch.turn_on: switch3
  - platform: gpio
    id: button_o1
    name: Light OFF
    pin:
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on: 200ms
        - delayed_off: 200ms
    on_press:
        then:
          - switch.turn_off: switch1
  - platform: gpio
    id: button_o2
    name: Music OFF
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on: 200ms
        - delayed_off: 200ms
    on_press:
        then:
          - switch.turn_off: switch2
  - platform: gpio
    id: button_o3
    name: Good spirits OFF
    pin:
      number: GPIO25
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
        - delayed_on: 200ms
        - delayed_off: 200ms
    on_press:
        then:
          - switch.turn_off: switch3

light:
  - platform: neopixelbus
    id: indicator_lights
    internal: true
    name: Indicators
    type: GRBW
    variant: SK6812
    pin: GPIO33
    num_leds: 3

#status_led:
#  pin:
#    number: GPIO0
#    inverted: true

logger:
  hardware_uart: UART0

api:

web_server:
  port: 80

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
